---
title: "pmlmcen_prior"
author: "haiyan yu"
date: "10/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, echo=FALSE}



library("ipw")
#library("pmipw")
library(cbdpm)
library("mice")
library("readxl")
library(xtable)

nmethods<-4
####number of methods: BL, PMM, IPW, AIPW
df.cbd <- read.csv("~/Downloads/Rpkg/cbdpm/CBD/cbd3ypm.csv")
#df.cbd <- read.csv("~/Downloads/Rpkg/cbdpm/man/cbd3ypmip.csv")
head(df.cbd)
#names(df.ipw)<-c("id","x1","x2","x3","a","y","block","pattern")
#df.cbd$cell <- 2 * (df.cbd$block - 1) + (df.cbd$a + 1)
#table(df.cbd$cell)

## Bootstrap
df.ipw <- df.cbd
df.ipw <- data.frame(df.ipw)

nid <- nrow(df.ipw)
head(df.ipw)
nid
max(df.ipw$id)
table(df.ipw$pattern,df.ipw$a)
round(prop.table(table(df.ipw$pattern,df.ipw$a), 2),4)
```
##Individual treatment effect==average, population

```{r}
dfpoint<-df.ipw[df.ipw$x1==27,]
#write.csv(df.ipw,"gdmdfipw.csv")

```
# W y2, pattern 3
```{r,warning=FALSE}
si=1#seq(1:2)
  yp<-df.cbd[,c(5,5+si+1,9)]
ti<-c(0,1)
detfishdfti<-data.frame(c(1,2))
names(detfishdfti)<-"ind"
for (sa in ti) {
#  yp<-df.cbd[,c(5,5+ti+1,9)]
#  sa<-sa[ti]
head(yp)
library(BAS)
library(lmvar)

detfishdf<-data.frame()
for (s in seq(1:2)) {
  ypv<-yp[yp$a==sa&yp$pattern==s,c(2)]
  ypv<-ypv[complete.cases(ypv)]
  ypv<-as.vector(ypv)
theta.start <- c(median(ypv), IQR(ypv)/2)
library(stats)
f <- function(x) {
    f1 <- 10*(x[3] - 10*theta(x[1],x[2]))
    f2 <- 10*(sqrt(x[1]^2+x[2]^2)-1)
    f3 <- x[3]
    return(f1^2 + f2^2 + f3^2)
}
mlogl3 <- function(theta, x) 
  {sum(-dcauchy(x, location = theta[1], scale = theta[2], log = TRUE)) }
out <- nlm(mlogl3, theta.start, x = ypv, hessian = TRUE)
fish <- out$hessian
print(fish)
fisherinf<-solve(fish)
#fisher(ypv, mu = TRUE, sigma = TRUE)
#Jeffreys(fish)

detfish<-det(fisherinf)
detfishdf<-rbind(detfishdf,detfish)
names(detfishdf)<-sa
}
detfishdfti<-cbind(detfishdfti,detfishdf)
}

print(detfishdfti)
detfishdfti<-detfishdfti[,c(2,3)]
detfishdftisqrt<-sqrt(detfishdfti)
```
```{r}

#x<-seq(0,1,length =100)
#https://stephens999.github.io/fiveMinuteStats/beta.html
x<-seq(0,1,by =0.01)
{
  par(mar = c(5, 4, 1.3, 8),      xpd = TRUE)
  plot(x,dbeta(x,detfishdfti[1,2],detfishdfti[2,2]),ylim=range(-0.002,0.021)
       #ylim=range(-0.002,0.023)
       , xlab="p",ylab="Density", lwd=3, lty=1,pch=20,cex.lab=1.2,cex.axis=1.2)#,xlim=range(x)
  legend("topright", inset = c(- 0.3, 0) ,legend = c("Insulin","Placebo","Uniform"),lwd=2,
       lty=c(1,2,3),col=c(1,2,3),pch=c(20,20,18),box.lwd = 0,box.col = "white",bg = "white")
    lines(x,dbeta(x,detfishdfti[1,2],detfishdfti[2,2]), lwd=3, lty=1,pch=20,col=1)

 lines(x,dbeta(x,detfishdfti[1,1],detfishdfti[2,1]), lwd=3, lty=2,col=2)
  points(x,dbeta(x,detfishdfti[1,1],detfishdfti[2,1]),  pch=20,col=2)
  
   par(mar=c(3,5,3,6), xpd = F)
      abline(v = c(0.13,0.87),  lwd=3, lty=4,col=4)
      abline(h = 1.8e-03,  lwd=3, lty=3,col=3,xlim=range(0,1))
      grid()
#legend("top", c("A=0","A=1","BL"),lwd=2,lty=c(1,2,3),col=c(1,2,3),pch=c(20,1,18))
#legend("top", c("Insulin","Placebo","Uniform"),lwd=2,lty=c(1,2,3),col=c(1,2,3),pch=c(20,1,18))

}
```

```{r}
xx<-dbeta(x,detfishdfti[1,2],detfishdfti[2,2])
quantile(xx, probs = seq(0, 1, 0.25))
```
```{r}

#detfishdfti<-detfishdfti[,c(2,3)]
#x<-seq(0,1,length =100)
#https://stephens999.github.io/fiveMinuteStats/beta.html
x<-seq(0,1,by =0.01)
{
#  par(mar = c(5, 4, 4, 8),     xpd = TRUE)
  plot(x,dbeta(x,detfishdfti[1,2],detfishdfti[2,2]),ylim=range(-0.002,0.023), xlab="p",ylab="Density", lwd=2, lty=1,pch=20)#,xlim=range(x)
  abline(h = 1.8e-03,  lwd=2, lty=3,col=3,xlim=range(0,1))
    lines(x,dbeta(x,detfishdfti[1,2],detfishdfti[2,2]), lwd=2, lty=1,pch=20,col=1)

 lines(x,dbeta(x,detfishdfti[1,1],detfishdfti[2,1]), lwd=2, lty=2,col=2)
  points(x,dbeta(x,detfishdfti[1,1],detfishdfti[2,1]),  pch=1,col=2)
  
   
      abline(v = c(0.13,0.87),  lwd=2, lty=4,col=4)

#grid()
#legend("top", c("A=0","A=1","BL"),lwd=2,lty=c(1,2,3),col=c(1,2,3),pch=c(20,1,18))
legend("top", c("Insulin","Placebo","Uniform"),lwd=2,lty=c(1,2,3),col=c(1,2,3),pch=c(20,1,18))

}
```
```{r}
#detfishdfti<-detfishdfti[,c(2,3)]
#x<-seq(0,1,length =100)
#https://stephens999.github.io/fiveMinuteStats/beta.html
x<-seq(0,1,by =0.01)
{
  plot(x,dbeta(x,detfishdfti[1,2],detfishdfti[2,2]),ylim=range(0,0.002), xlab="p",ylab="Density", lwd=2, lty=1,pch=20)#,xlim=range(x);, cex=3
    lines(x,dbeta(x,detfishdfti[1,2],detfishdfti[2,2]), lwd=2, lty=1,pch=20,col=1)

 lines(x,dbeta(x,detfishdfti[1,1],detfishdfti[2,1]), lwd=2, lty=2,col=2)
  points(x,dbeta(x,detfishdfti[1,1],detfishdfti[2,1]),  pch=1,col=2)
  
   abline(h = 1.8e-03,  lwd=2, lty=3,col=3)
   abline(v = c(0.13,0.87),  lwd=2, lty=4,col=4)
grid()
#legend("top", c("A=0","A=1","BL"),lwd=2,lty=c(1,2,3),col=c(1,2,3),pch=c(20,1,18))
legend("top", c("Insulin","Placebo","Uniform"),lwd=2,lty=c(1,2,3),col=c(1,2,3),pch=c(20,1,18))
}
```


```{r}
#Creating graphs with two y-axes
set.seed(1)
#df <- data.frame(x=1:100, 
#                 y1=-0.001+0.002/(1:100)+rnorm(100,0,5e-5),
#                 y2=0.05+0.0015*(0:99)+rnorm(100,0,1e-2))

{
  ticks.1 <- seq(-0.001,0.001,0.0001)
ticks.2 <- seq(0.05,0.2,0.01)

plot(x, dbeta(x,detfishdfti[1,1],detfishdfti[2,1]), type="l", yaxt="n", xlab="X", ylab="", col="blue")
axis(2, at=ticks.1, col.ticks="blue", col.axis="blue")
par(new=T)
plot(x, dbeta(x,detfishdfti[1,2],detfishdfti[2,2]), type="l", yaxt="n", xlab="", ylab="", col="red")
axis(4, at=ticks.2, col.ticks="red", col.axis="red")
}
```


```{r}

#x<-seq(0,1,length =100)
#https://stephens999.github.io/fiveMinuteStats/beta.html
pdf(file = 
  "detfishdftisqrt.pdf",width =5.6,height =4)
x<-seq(0,1,by =0.01)
{
  par(mar = c(5, 4, 1.3, 8),      xpd = TRUE)
  plot(x,dbeta(x,detfishdftisqrt[1,2],detfishdftisqrt[2,2]),ylim=range(-0.002,1.21)
       #ylim=range(-0.002,0.023)
       , xlab="p",ylab="Density", lwd=3, lty=1,pch=20,cex.lab=1.2,cex.axis=1.2)#,xlim=range(x)
  legend("top", legend = c("Insulin","Placebo","Uniform"),lwd=2,
       lty=c(1,2,3),col=c(1,2,3),pch=c(20,20,18),bg = "white")#,box.lwd = 0,box.col = "white"
    lines(x,dbeta(x,detfishdftisqrt[1,2],detfishdftisqrt[2,2]), lwd=3, lty=1,pch=20,col=1)

 lines(x,dbeta(x,detfishdftisqrt[1,1],detfishdftisqrt[2,1]), lwd=3, lty=2,col=2)
  points(x,dbeta(x,detfishdftisqrt[1,1],detfishdftisqrt[2,1]),  pch=20,col=2)
  
   par(mar=c(3,5,3,6), xpd = F)
      abline(v = c(0.13,0.87),  lwd=3, lty=4,col=4)
      abline(h = 0.12,  lwd=3, lty=3,col=3,xlim=range(0,1))
      grid()
#legend("top", c("A=0","A=1","BL"),lwd=2,lty=c(1,2,3),col=c(1,2,3),pch=c(20,1,18))
#legend("top", c("Insulin","Placebo","Uniform"),lwd=2,lty=c(1,2,3),col=c(1,2,3),pch=c(20,1,18))

}
print(detfishdftisqrt)
dev.off()
```

#Normanization



```{r}
sumv1<-sum(detfishdftisqrt[,1])
sumv2<-sum(detfishdftisqrt[,2])
detfishnor<-data.frame(detfishdftisqrt[,1]/sumv1,detfishdftisqrt[,2]/sumv2)
names(detfishnor)<-c("a1","a2")
  df<-detfishnor
#x<-seq(0,1,length =100)
#https://stephens999.github.io/fiveMinuteStats/beta.html
x<-seq(0,1,by =0.01)
prior<-{
  par(mar = c(5, 4, 1.3, 8),      xpd = TRUE)
  plot(x,dbeta(x,df[1,2],df[2,2]),ylim=range(-0.002,7.21)
       #ylim=range(-0.002,0.023)
       , xlab="p",ylab="Density", lwd=3, lty=1,pch=20,cex.lab=1.2,cex.axis=1.2)#,xlim=range(x)
  legend("topright" #,inset = c(- 0.3, 0) 
         ,legend = c("Insulin","Placebo","Uniform")
         ,lwd=2,
       lty=c(1,2,3),col=c(1,2,3),pch=c(20,20,18), box.lwd = 1#0
      # , box.col = "white"
    #   , bg = "white"
       )
    lines(x,dbeta(x,df[1,2],df[2,2]), lwd=3, lty=1,pch=20,col=1)

 lines(x,dbeta(x,df[1,1],df[2,1]), lwd=3, lty=2,col=2)
  points(x,dbeta(x,df[1,1],df[2,1]),  pch=20,col=2)
  
   par(mar=c(3,5,3,6), xpd = F)
      abline(v = c(0.1),  lwd=3, lty=4,col=4)
      abline(h = 1.0,  lwd=3, lty=3,col=3,xlim=range(0,1))
      grid()
#legend("top", c("A=0","A=1","BL"),lwd=2,lty=c(1,2,3),col=c(1,2,3),pch=c(20,1,18))
#legend("top", c("Insulin","Placebo","Uniform"),lwd=2,lty=c(1,2,3),col=c(1,2,3),pch=c(20,1,18))
prior+ggsave("prior.pdf", width = 5, height = 4)
}
#print(df)

#save(prior)
```


```{r}
sumv1<-sum(detfishdftisqrt[,1])
sumv2<-sum(detfishdftisqrt[,2])
detfishnor<-data.frame(detfishdftisqrt[,1]/sumv1,detfishdftisqrt[,2]/sumv2)
names(detfishnor)<-c("a1","a2")
  df<-detfishnor
#x<-seq(0,1,length =100)
#https://stephens999.github.io/fiveMinuteStats/beta.html
x<-seq(0,1,by =0.01)
prior<-{
  plot(x,dbeta(x,df[1,2],df[2,2]),ylim=range(-0.002,7.21)
       #ylim=range(-0.002,0.023)
       , xlab="p",ylab="Density", lwd=3, lty=1,pch=20,cex.lab=1.2,cex.axis=1.2)#,xlim=range(x)
  legend("topright" #,inset = c(- 0.3, 0) 
         ,legend = c("Insulin","Placebo","Uniform")
         ,lwd=2,
       lty=c(1,2,3),col=c(1,2,3),pch=c(20,20,18), box.lwd = 1#0
      # , box.col = "white"
    #   , bg = "white"
       )
    lines(x,dbeta(x,df[1,2],df[2,2]), lwd=3, lty=1,pch=20,col=1)

 lines(x,dbeta(x,df[1,1],df[2,1]), lwd=3, lty=2,col=2)
  points(x,dbeta(x,df[1,1],df[2,1]),  pch=20,col=2)
  
   par(mar=c(3,5,3,6), xpd = F)
      abline(v = c(0.1),  lwd=3, lty=4,col=4)
      abline(h = 1.0,  lwd=3, lty=3,col=3,xlim=range(0,1))
      grid()
#legend("top", c("A=0","A=1","BL"),lwd=2,lty=c(1,2,3),col=c(1,2,3),pch=c(20,1,18))
#legend("top", c("Insulin","Placebo","Uniform"),lwd=2,lty=c(1,2,3),col=c(1,2,3),pch=c(20,1,18))
prior+ggsave("prior.pdf", width = 5, height = 4)
}
#print(df)

#save(prior)
```

```{r}
#https://stat.ethz.ch/R-manual/R-devel/library/stats/html/Beta.html
#x <- seq(0, 1, length = 21)
x<-seq(0,1,by =0.01)
dbeta(x, 1, 1)
pbeta(x, 1, 1)

## Visualization, including limit cases:
pl.beta <- function(a,b, asp = if(isLim) 1, ylim = if(isLim) c(0,1.1)) {
  if(isLim <- a == 0 || b == 0 || a == Inf || b == Inf) {
    eps <- 1e-10
    x <- c(0, eps, (1:7)/16, 1/2+c(-eps,0,eps), (9:15)/16, 1-eps, 1)
  } else {
    x <- seq(0, 1, length = 1025)
  }
  fx <- cbind(dbeta(x, a,b), pbeta(x, a,b), qbeta(x, a,b))
  f <- fx; f[fx == Inf] <- 1e100
  matplot(x, f, ylab="", type="l", ylim=ylim, asp=asp,
          main = sprintf("[dpq]beta(x, a=%g, b=%g)", a,b))
  abline(0,1,     col="gray", lty=3)
  abline(h = 0:1, col="gray", lty=3)
  legend("top", paste0(c("d","p","q"), "beta(x, a,b)"),
         col=1:3, lty=1:3, bty = "n")
  invisible(cbind(x, fx))
}
pl.beta(3,1)
pl.beta(0.1563,0.8437,ylim=range(0,3))#,cex=1.3)#,cex.lab=1.2,cex.axis=1.2)
{
  par(  mfrow=c(1,2))
pl.beta(df[1,2],df[2,2],ylim=range(0,3))
pl.beta(df[1,1],df[2,1],ylim=range(0,3))
#  dev.off()

} 
```
